# MySQL 設定ファイル（bind-address = 0.0.0.0）
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]
    bind-address = 0.0.0.0
    character-set-server = utf8mb4
    collation-server = utf8mb4_general_ci

    [client]
    default-character-set = utf8mb4

    [mysql]
    default-character-set = utf8mb4

---

# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root12345
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: config-volume
          mountPath: /etc/mysql/conf.d
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: config-volume
        configMap:
          name: mysql-config
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc


---

# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306